# Football Simulation Configuration

# Pitch dimensions (half FIFA pitch)
pitch_width: 34.0  # meters
pitch_length: 52.0  # meters

# Time settings
dt: 0.066  # seconds per tick (≈15 FPS)
max_game_time: 900  # seconds (15 minutes for enhanced simulation)
max_ticks_without_change: 900  # ticks before ending due to inactivity (1 minute)

# Realism settings
realism_level: "empirical"  # "toy" or "empirical"

# Team formations (7-a-side)
formations:
  team_0:
    - role: "goalkeeper"
      x: 17.0
      y: 5.0
    - role: "defender" 
      x: 10.0
      y: 15.0
    - role: "defender"
      x: 24.0
      y: 15.0
    - role: "midfielder"
      x: 17.0
      y: 25.0
    - role: "midfielder"
      x: 8.0
      y: 30.0
    - role: "midfielder"
      x: 26.0
      y: 30.0
    - role: "forward"
      x: 17.0
      y: 40.0
  
  team_1:
    - role: "goalkeeper"
      x: 17.0
      y: 47.0
    - role: "defender"
      x: 10.0
      y: 37.0
    - role: "defender"
      x: 24.0
      y: 37.0
    - role: "midfielder"
      x: 17.0
      y: 27.0
    - role: "midfielder"
      x: 8.0
      y: 22.0
    - role: "midfielder"
      x: 26.0
      y: 22.0
    - role: "forward"
      x: 17.0
      y: 12.0

# Logging settings
logging:
  verbose: true
  csv_output: "match_log.csv"
  xes_output: "match_log.xes"
